### ISSUE TITLE
Configure the size of the cache stored on file system

### ISSUE THREAD

**Issue by amotzte** [npm/cacache#20]
Hi @isaacs 
I'm looking for a library to manage a local-file-system cache to be used in a node.js server.
Maybe I'm way off here, but I'm trying to understand if cacache can fit. The problem is that I need a TTL and (more importantly)  MAX size features (So I can control the size that cache library take on fs so it will not explode) is it possible to do this with cacache? Looking at the code, I could not see a way to do this.

I've also been playing with the idea of using your ```lru-cache``` to "mirror" the file system cache library. Bassically store the files on fs and then add them to the lru-cache. Then when I get the ```dispose``` event I'll delete the file (So this  basically mean I will have LRU cache on file system)

Since I run on docker I don't have a risk of lru-cache inRam cache to get out of sync with fs (Because if the server crashes/stop the container will be killed and recreated with new clean fs)

Does this make any sense ?

**Comment by isaacs** [comment]
An lru-cache + cacache system sounds pretty cool, and that's definitely the approach I'd explore first.  You may want to look at http://npm.im/async-cache as a way to hook them together.  (Async-cache is lru-cache where items are fetched asynchronously.  It's a bit dated, so no fancy promise handling etc, but there's not a lot to it, so it's fairly stable.)  Given the context of a docker container, where a crash means the fs is blown away anyhow, that's probably the best way to go.

I don't think it's a great idea to add an LRU or max size to cacache itself, though.  It would require making this thing a bit more bloated than I'd like it to be, since managing the LRU info and tracking size is a whole other job.

If you wanted a persistently size-limited LRU-pruned file system cache, that's another interesting idea, but would require some additional orchestration on top of cacache to make it work.  Doing so in a way that's not prone to parallel processes clobbering one another, or falling over by trying to keep too much in memory, would be a bit tricky, but probably doable.  I know it's not what you're necessarily needing, but it'd be a cool project if someone wanted to take it on, and cacache would probably be a good fit for the underlying storage layer.

So, `WONTFIX`, but I think you should pursue it :)

**Comment by amotzte** [comment]
@isaacs, Thanks for the quick reply!

I already started working on an lru-cache + cacache module and it looks pretty good (Both lru-cache and cache had everything I needed 😄). 

Also manage solve the persistency problem (for non-docker) by using cacache.ls and populate  the lru-cache on startup.
If you interested, you can see here:
https://gist.github.com/amotzte/8a87cc7fd53ffd02d3b8fa7d52d4434a#file-lru-cacache-js-L64-L75 

Will test it more and will publish it if all goes well.

**Comment by AbdulBsit** [comment]
Your gist link is dead, any updates on this? @amotzte
